# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel-Technical-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxGesture', '~> 3.0.2'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'ProgressHUD', '~> 13.4'
  pod 'Swinject'

  # Pods for Marvel-Technical-Test


end
