//
//  ResourcingText.swift
//  File autogenerated
//
//  Created by Jorge Morán Palomeque.
//  jorgemoranp@gmail.com
//

import Foundation

public class RTexts {

    
    /**
      Matching with: Escribe cualquier usuario para continuar, Escribe cualquier usuario para continuar
    */
	public let user_placeholder: String = NSLocalizedString("user.placeholder", comment: "")
    
    /**
      Matching with: Aceptar, Aceptar
    */
	public let accept: String = NSLocalizedString("accept", comment: "")
    
    /**
      Matching with: Cancelar, Cancelar
    */
	public let cancel: String = NSLocalizedString("cancel", comment: "")
    
    /**
      Matching with: Acceder, Acceder
    */
	public let access: String = NSLocalizedString("access", comment: "")
    
    /**
      Matching with: Inicia sesión para acceder a la app, Inicia sesión para acceder a la app
    */
	public let login_title: String = NSLocalizedString("login.title", comment: "")
    
    /**
      Matching with: Contraseña, Contraseña
    */
	public let password: String = NSLocalizedString("password", comment: "")
    
    /**
      Matching with: Escribe cualquier contraseña para continuar, Escribe cualquier contraseña para continuar
    */
	public let password_placeholder: String = NSLocalizedString("password.placeholder", comment: "")
    
    /**
      Matching with: Recordar contraseña, Recordar contraseña
    */
	public let password_remenber: String = NSLocalizedString("password.remenber", comment: "")
    
    /**
      Matching with: Registrarse, Registrarse
    */
	public let register: String = NSLocalizedString("register", comment: "")
    
    /**
      Matching with: Se ha producido un error, Se ha producido un error
    */
	public let deafult_error: String = NSLocalizedString("deafult_error", comment: "")
    
    /**
      Matching with: Usuario, Usuario
    */
	public let user: String = NSLocalizedString("user", comment: "")
}